### ISSUE TITLE
Quoting example: Error invalid BigNumber value

### ISSUE THREAD

**Issue by findtoni** [Uniswap/examples#29]
Hi DX team,

I tried running the quoting example after following the steps, but I keep getting this error.

1. Run `yarn install`
2. Set mainnet rpc url
3. `yarn run`

<img width="599" alt="Screenshot 2023-01-17 at 06 31 03" src="https://user-images.githubusercontent.com/35571969/212817746-d3b3a2e7-c29e-4cca-a609-618f78a1ffef.png">

<img width="1440" alt="Screenshot 2023-01-17 at 06 30 57" src="https://user-images.githubusercontent.com/35571969/212817741-e8678e43-2be6-403e-8079-b5fb44b3694c.png">

**Comment by dannydaniil** [comment]
Thanks for openning the issue! We'll be looking into it

**Comment by dannydaniil** [comment]
Should hav been addresed :)
