### ISSUE TITLE
Unhandled runtime error

### ISSUE THREAD

**Issue by s-pcode** [Uniswap/examples#45]
`Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="liquidity()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)`

I'm encountering this issue when I change chain from ethereum to polygon.

**Comment by s-pcode** [comment]
The issue was with computePoolAddress function which was not able to find the pool address for that particular pair of token. I had to query uniswap v3 subgraph for fetch pool address of that pair and then it worked.

**Comment by shuzhiwen** [comment]
> The issue was with computePoolAddress function which was not able to find the pool address for that particular pair of token. I had to query uniswap v3 subgraph for fetch pool address of that pair and then it worked.

Can I have a code that solves the problem? Thanks
